### ISSUE TITLE
Centering the plasma (FPI) measurements on load

### ISSUE THREAD

**Issue by ericthewizard** [amanotk/mms-bowshock#1]
I was just looking at your code in download.py, i.e., line 193:

```
        pyspedas.mms.fpi(
            data_rate="fast", datatype=["des-moms", "dis-moms"], varformat=fmt, **kwargs
        )
```

The FPI (and HPCA) measurements are at the start of the accumulation interval, while the other measurements (e.g., FGM, SCM, FEEPS, etc) are at the middle of the accumulation interval. If you do calculations with these, you'll probably want to center the FPI measurements on loading the data with the `center_measurement=True` option.

**Comment by amanotk** [comment]
Fixed it. Thank you for the suggestion!
